### ISSUE TITLE
create demo instance or at least show screenshots

### ISSUE THREAD

**Issue by COLABORATI** [beave/sagan#102]
i want to see it before spending too much time with something I might not need, please make a demo instance available or at least publish some screenshots, thanks!

**Comment by beave** [comment]
Sagan works similar to Suricata and Snort, but with logs instead of network packets.   Like Suricata/Snort,  Sagan does not come with a GUI.   You can use GUI's that are compatible with Snort/Sagan (likey Snorby,  Squil, etc).   There are a lot of interfaces out there.   Sagan is simply the engine to provide the data to GUI.   It does not contain anything very "screenshot" worthy in itself. 

Please let me know if you have any other questions.
