### ISSUE TITLE
Use of Remove_Spaces function

### ISSUE THREAD

**Issue by YoichSec** [beave/sagan#89]
The remove_spaces function from util.c is often used as though it removes spaces directly from the argument variable. However, it does not. This can result in spaces being left when they are expected to have been removed. 

Example correct usage (rules.c 356-357):
```
flow_a = Remove_Spaces(Sagan_Var_To_Value(tokennet));
if (!strcmp(flow_a, "any") || !strcmp(flow_a, Remove_Spaces(tokennet))) {
```

Example incorrect usage (rules.c 662-666):
```
Remove_Spaces(arg);

if (!strcmp(arg, "md5")) {
rulestruct[counters->rulecount].s_find_hash_type = PARSE_HASH_MD5;
}
```
If 'arg' contained spaces before the Remote_Spaces function is called, the stcmp is passed a value with the space still there. 

I first saw this with default_proto, but it occurs often in a number of different files. It should be simple to change in-line by simply adding 'arg = ' or the equivalent in front. I haven't personally run into huge issues with rule-parsing as a result of this, but I'm submitting an issue for awareness.

**Comment by beave** [comment]
Actually,  because we are dealing with threaded data,  we don't deal with strings in traditional method like this: 

char *SomeFunction( char *inputstring )
{

char *return_str = NULL; 

/* Do things */

return(return_str); 
}


Doing the above will lead to all sorts of problems.   Mostly because more than one thread might be accessing the function at any given point.   The return data has the potential of getting corrupted. 

The "incorrect" use is actually more correct :)   

We pass the variable on the threads stack.  We then modify the data on the stack,  so no "return" is needed.   In fact,  that function needs to moved from a prototype of:

char *Remove_Spaces(char *s)

to 

void *Remove_Spaces(char *s)

and the "return" dropped.   Technically,  the "return" works because it is returning the same data thats on the stack.  While it works either way,  it's terribly inconsistent. 

I've been slowly re-working functions for consistency.   For example,  I recent did this function:

https://github.com/beave/sagan/blob/master/src/util.c#L918-L933

Note the lack of "return".   I know it looks weird :)

Here's another example from but from Suricata: 

https://github.com/inliniac/suricata/blob/master/src/util-time.c#L179-L193


You'll sometimes notice I've done crappy things like:

static __thread char buffer[4096];

Then,  we have a return pointer to the "buffer".  This is a kludge to accomplish the same thing.  The problem is,  it isn't portable at all.

**Comment by beave** [comment]
Oh ..  And example call from ipc.c. 

Sagan_u32_Time_To_Human(xbit_ipc[i].xbit_expire, time_buf, sizeof(time_buf));

time_buf is passed,  but also "becomes" the human readable output.

**Comment by beave** [comment]
Example from a quickly modified classifications.c

--<code>-- 

        printf("Pre: |%s|\n", laststring);
        Remove_Spaces(laststring);
        printf("Post: |%s|\n", laststring);

--</code>--

--<output>--

Pre: | correlated-attack|
Post: |correlated-attack|
Pre: | unsuccessful-admin|
Post: |unsuccessful-admin|
Pre: | exploit-attempt|
Post: |exploit-attempt|
Pre: | program-error|
Post: |program-error|

--</output>-- 

It's probably hard to tell in the output on Github, but the "Pre" contains a space".  The Post has the space removed.

**Comment by YoichSec** [comment]
Hmm. I believe you, but I did get stuck with a remaining space in the default_proto token after "Remove_Spaces(Sagan_Var_To_Value(arg));" that I verified by printing to a log message. It went away after I added "arg=" in front. Let me take another look this weekend. Thanks for the detailed explanation! I may be learning something :)

**Comment by beave** [comment]
I don't doubt you at all.  Again, it goes back to consistency.   Remove_Spaces modifies on the stack and returns pointer to the stack.   Sagan_Var_To_Value does a __static kludge but with a return.   In a perfect world,  it would look like this:

Sagan_Var_To_Value(arg);
Remove_Spaces(arg); 

/* Now do something with arg */

It being stacked up like that depends on a return value.   Some functions "return" pointers,  others modify thread stack data.   

What line of code are you looking at that keeps the spaces?

**Comment by beave** [comment]
wait.. do you mean you have:

arg = Remove_Spaces(Sagan_Var_To_Value(arg));

?? Is so, holy crap..  We're going in a really weird direction!  It that works,  it's sorta weird, so bad and awesome all at once.... hahahah.

**Comment by beave** [comment]
Hahaha. yeah.. i see what you are saying....  I think I see why... 

Remove_Spaces(arg);

.. Works because "arg" is a pointer being passed on the stack.    Since we are calling a function (Sagan_Var_To_Value),  I'm not sure where (if?) there's a pointer address.  You supply a pointer with the "arg =". 

Again..  totally inconsistent on my part.   I need to re-work Sagan_Var_To_Value.   I'll get that.

**Comment by YoichSec** [comment]
Haha yes. That is what I did. It's only in one place and isn't pushed yet, so maybe we can figure out the correct approach. The lines in rule.c are currently 575 to 597. If I had "default_proto: icmp" in a rule, arg remained ' icmp' with a space throughout the checks and all of them fail.

**Comment by YoichSec** [comment]
Ah, OK that makes sense. I'll hold off on doing hacker-tier-programming crap on the other parts then :)

**Comment by beave** [comment]
Thinking about it, the Sagan_Var_To_Value should return a pointer to the data.  Anyways,  it doesn't matter,  it's freaking broken :) 

I'll re-work that function ASAP.    If you want,  you can go ahead and using your "arg ="..  I'll let you know when/how to modify it..   

Or you can wait..  Whatever works for you.    Fun stuff though.  :) 

I'll likely leave Remove_Spaces the way it is.  It's technically not terribly,  just not consistent.   I can start re-working Sagan_Var_To_Value Monday.   Cool?

**Comment by YoichSec** [comment]
Cool. I'll make the other changes for now and grab your updates next week. Feel free to close this issue whenever.
