### ISSUE TITLE
Is bro-intel still supported?

### ISSUE THREAD

**Issue by CyberTaoFlow** [beave/sagan#90]
For awhile (at least since the YAML switchover) I have been unable to get bro-intel files to work.
 
[*] [04/10/2017 15:28:27] - 
[*] [04/10/2017 15:28:27] - Bro Intel::ADDR Loaded: 0
[*] [04/10/2017 15:28:27] - Bro Intel::DOMAIN Loaded: 0
[*] [04/10/2017 15:28:27] - Bro Intel::FILE_HASH Loaded: 0
[*] [04/10/2017 15:28:27] - Bro Intel::URL Loaded: 0
[*] [04/10/2017 15:28:27] - Bro Intel::SOFTWARE Loaded: 0
[*] [04/10/2017 15:28:27] - Bro Intel::EMAIL Loaded: 0
[*] [04/10/2017 15:28:27] - Bro Intel::USER_NAME Loaded: 0
[*] [04/10/2017 15:28:27] - Bro Intel::FILE_NAME Loaded: 0
[*] [04/10/2017 15:28:27] - Bro Intel::CERT_HASH Loaded: 0
[*] [04/10/2017 15:28:27] - Bro Intel Duplicates Detected: 0

Should this be working in the 1.1.6 and 1.1.7 builds?

If so I can do a gdb debug but if support has been dropped i wont waste my time.

**Comment by beave** [comment]
It should be still supported.  I'll need to test to see if I can replicate .  I believe I was getting my test data from criticalstack.   Can you point me to a copy of your data?  Thanks .On Apr 10, 2017 4:52 PM, Psipher Diaz <notifications@github.com> wrote:For awhile (at least since the YAML switchover) I have been unable to get bro-intel files to work.
[] [04/10/2017 15:28:27] -
[] [04/10/2017 15:28:27] - Bro Intel::ADDR Loaded: 0
[] [04/10/2017 15:28:27] - Bro Intel::DOMAIN Loaded: 0
[] [04/10/2017 15:28:27] - Bro Intel::FILE_HASH Loaded: 0
[] [04/10/2017 15:28:27] - Bro Intel::URL Loaded: 0
[] [04/10/2017 15:28:27] - Bro Intel::SOFTWARE Loaded: 0
[] [04/10/2017 15:28:27] - Bro Intel::EMAIL Loaded: 0
[] [04/10/2017 15:28:27] - Bro Intel::USER_NAME Loaded: 0
[] [04/10/2017 15:28:27] - Bro Intel::FILE_NAME Loaded: 0
[] [04/10/2017 15:28:27] - Bro Intel::CERT_HASH Loaded: 0
[*] [04/10/2017 15:28:27] - Bro Intel Duplicates Detected: 0
Should this be working in the 1.1.6 and 1.1.7 builds?
If so I can do a gdb debug but if support has been dropped i wont waste my time.

**Comment by CyberTaoFlow** [comment]
I am also using critical stack for testing but in production using a custom built data file. Ill do a debug and see what I can find out.

**Comment by beave** [comment]
I'll look tonight.  It's been a while since I tested that code, so there might be some bit rot.

**Comment by beave** [comment]
Hey -  config-yaml.c in the bro-intel section was looking for "url" and not "filename".  I've pushed up a fix for this.  Looks like it's properly loading the data now!  Thank you for reporting.  Let me know if it works out for you and I'll close this ticket! 


[*] Bro Intel Processor Loading File: /opt/critical-stack/frameworks/intel/master-public.bro.dat.
[*] Bro Intel::ADDR Loaded: 24738
[*] Bro Intel::DOMAIN Loaded: 17922
[*] Bro Intel::FILE_HASH Loaded: 162
[*] Bro Intel::URL Loaded: 151
[*] Bro Intel::SOFTWARE Loaded: 0
[*] Bro Intel::EMAIL Loaded: 0
[*] Bro Intel::USER_NAME Loaded: 0
[*] Bro Intel::FILE_NAME Loaded: 0
[*] Bro Intel::CERT_HASH Loaded: 0
[*] Bro Intel Duplicates Detected: 0

**Comment by CyberTaoFlow** [comment]
Sweet looks good thanks!  Where can I find out more about  bluedot?  I work for an MSP/ISP in the chicago area and we are always interested in good intel sources and possibly contributing to bluedot if that would be helpful.

All the literature I have found indicates it is only provided to your MSP clients as part of your solution.  Is it possible for third parties using sagan to sign up for bluedot?

**Comment by beave** [comment]
Funny you brought this up.   Right now, we use it at our MSP (Quadrant).   We are looking at opening it up in the near future.    All of our Sagan sensors out in the field actively query the Bluedot API.   It's a pretty awesome system and we're going to want testers. 

If you can,  hit me up via e-mail.  My e-mail is cclark@quadrantsec.com.   I'll hit you up when we go into testing with the API.  

I'm going to go ahead and close this issue out.   Let me know if you run into any other issues.
